"""Schema revision 0001."""
from alembic import op
import sqlalchemy as sa

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('api_key_ciphertext', sa.Text(), nullable=False),
    sa.Column('secret_key_ciphertext', sa.Text(), nullable=False),
    sa.Column('allow_live_trading', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('total_wallet_balance', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('total_unrealized_pnl', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_snapshots_captured_at'), 'account_snapshots', ['captured_at'], unique=False)
    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('position_side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('margin', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('liquidation_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('trailing_pct', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('peak_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', 'position_side')
    )
    op.create_index(op.f('ix_positions_account_id'), 'positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('risk_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('max_margin_ratio', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('max_order_notional', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('max_daily_loss', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('max_leverage', sa.Integer(), nullable=False),
    sa.Column('liquidation_buffer_pct', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('trading_halted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_configs_account_id'), 'risk_configs', ['account_id'], unique=True)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('strategy_type', sa.String(length=40), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('last_signal', sa.String(length=10), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_account_id'), 'strategies', ['account_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('position_side', sa.String(length=10), nullable=False),
    sa.Column('client_order_id', sa.String(length=36), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_table('strategy_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_events_created_at'), 'strategy_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_events_strategy_id'), 'strategy_events', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('strategy_events')
    op.drop_table('orders')
    op.drop_table('strategies')
    op.drop_table('risk_configs')
    op.drop_table('positions')
    op.drop_table('login_sessions')
    op.drop_table('account_snapshots')
    op.drop_table('users')
    op.drop_table('exchange_accounts')
