"""Schema revision 0003."""
from alembic import op
import sqlalchemy as sa

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protection_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('position_side', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('client_algo_id', sa.String(length=36), nullable=False),
    sa.Column('algo_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_algo_id')
    )
    op.create_index(op.f('ix_protection_orders_account_id'), 'protection_orders', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('protection_orders')
