import assert from "node:assert/strict";
import fs from "node:fs";
import { CLIENT_AGENTS, detectClientAgent, publicClientAgent, resolveClientAgent, safeReasoning } from "../src/services/client-agents.js";
import { parseAgentRouting, matchAgentRule, agentReasoning, orderAgentChannels } from "../src/services/agent-routing.js";
import { deviceFromUa } from "../src/utils.js";
import { publicRunError } from "../src/services/upstream/public-error.js";
import { mapLog } from "../src/routes/log.js";
import { withClientAgent, clientAgentAudit } from "../src/services/client-agent-context.js";
const z = "ZCode/3.14.3 ai-sdk/provider-utils/4.0.39 runtime/node.js/24";
const o = "opencode/1.18.31 ai-sdk/provider-utils/4.0.23 runtime/node.js/24";
assert.deepEqual(detectClientAgent({ "user-agent": z }), { id: "zcode", version: "3.14.3", source: "user-agent", confidence: "heuristic", conflict: false });
assert.equal(detectClientAgent({ "user-agent": o }).id, "opencode");
assert.equal(deviceFromUa(z), "Node.js 24");
assert.equal(deviceFromUa(o), "Node.js 24");
assert.equal(detectClientAgent({ "user-agent": "node" }).id, "");
assert.equal(detectClientAgent({ "user-agent": "OpenAI/JS 5.0" }).id, "");
assert.equal(detectClientAgent({ "user-agent": "Anthropic/JS 1.0" }).id, "");
assert.equal(detectClientAgent({ "user-agent": "codex_cli_rs/0.123.0 (Windows 10.0)" }).id, "codex");
const tui = "codex-tui/0.160.0 (Ubuntu 22.4.0; x86_64) xterm-256color";
assert.equal(detectClientAgent({ "user-agent": tui }).id, "codex");
assert.equal(detectClientAgent({ "user-agent": tui }).confidence, "heuristic");
assert.equal(deviceFromUa(tui), "Ubuntu 22.4.0");
assert.equal(detectClientAgent({ "user-agent": "GeminiCLI/0.10.0/gemini-2.5-pro (linux; x64)" }).id, "gemini-cli");
assert.equal(detectClientAgent({ "user-agent": "CloudCodeVSCode/1.2.3 proxy_client=geminicli" }).id, "gemini-cli");
assert.equal(detectClientAgent({ "user-agent": "CloudCodeVSCode/1.2.3" }).id, "");
assert.equal(detectClientAgent({ "user-agent": "CloudCodeVSCode/1.2.3 (proxy_client=geminicli-fake)" }).id, "");
assert.equal(detectClientAgent({ "user-agent": "GeminiCLI-vscode/0.10.0/gemini-2.5-pro (linux; x64)" }).id, "gemini-cli");
assert.equal(detectClientAgent({ "user-agent": "GeminiCLI/0.10.0 CloudCodeVSCode/1.2.3 proxy_client=geminicli" }).conflict, false);
assert.equal(detectClientAgent({ "user-agent": "RooCode/3.20.0" }).id, "roo-code");
assert.equal(detectClientAgent({ "user-agent": "roo-code/3.20.0" }).id, "roo-code");
assert.equal(detectClientAgent({ "user-agent": "Go-http-client/1.1", "x-title": "Roo Code", "http-referer": "https://github.com/RooVetGit/Roo-Cline" }).id, "roo-code");
assert.equal(detectClientAgent({ "x-title": "Roo Code", "http-referer": "https://evil.invalid/?source=github.com/RooVetGit/Roo-Cline" }).id, "");
assert.equal(detectClientAgent({ "user-agent": "Go-http-client/1.1", "x-title": "Roo Code", "http-referer": "https://github.com/RooVeterinaryInc/Roo-Cline" }).id, "");
assert.equal(detectClientAgent({ originator: "codex_vscode" }).id, "codex");
assert.equal(detectClientAgent({ "user-agent": "Codex Desktop/1.2.3 (macOS)" }).id, "codex");
assert.equal(detectClientAgent({ "x-app": "claude-cli" }).id, "");
const aider = { "user-agent": "litellm/1.80.0", "x-title": "Aider", "http-referer": "https://aider.chat" };
assert.equal(detectClientAgent(aider).id, "aider");
assert.equal(detectClientAgent(aider).conflict, false);
assert.equal(detectClientAgent(aider).confidence, "declared");
assert.equal(detectClientAgent({ ...aider, "http-referer": "https://aider.chat.evil" }).id, "litellm");
assert.equal(detectClientAgent({ "http-referer": "https://www.continue.dev/", "x-openrouter-title": "Continue" }).id, "continue");
assert.equal(detectClientAgent({ "http-referer": "https://goose-docs.ai", "x-title": "goose" }).id, "goose");
assert.equal(detectClientAgent({ "user-agent": "GitHubCopilotChat/0.35.0" }).id, "copilot");
assert.equal(detectClientAgent({ "http-referer": "https://goose-docs.ai", "x-title": "goose", "user-agent": "NewAPI/1.0" }).id, "new-api");
assert.equal(detectClientAgent({ "user-agent": "OpenAI/JS 5.0", "copilot-integration-id": "vscode-chat", "agent-session-id": "foo" }).id, "");
assert.equal(detectClientAgent({ "x-title": "Z Code@electron", "x-zcode-app-version": "3.14.3" }).id, "zcode");
assert.equal(detectClientAgent({ "user-agent": "NewAPI/1.0 codex-tui/0.160.0", originator: "codex_cli_rs" }).id, "new-api");
assert.equal(publicClientAgent({ id: "", source: "unknown" }, tui).id, "codex");
assert.equal(publicClientAgent('{"id":"","source":"unknown"}', tui).version, "0.160.0");
assert.equal(publicClientAgent({ id: "", source: "disabled" }, tui).id, "");
assert.equal(mapLog({ ...historicalFixture(), user_agent: tui, detail: '{"client_agent":{"id":"","source":"unknown"}}' }, { isAdmin: true }).client_agent.id, "codex");
function historicalFixture() { return { id: 3, type: 2, device: "未知设备" }; }
const relay = detectClientAgent({ "user-agent": tui, "x-ooapi-agent": "sub2api" });
assert.equal(relay.id, "sub2api");
assert.equal(relay.conflict, false);
assert.equal(relay.confidence, "declared");
assert.deepEqual(relay.reported_client, { id: "codex", version: "0.160.0", source: "user-agent", confidence: "heuristic" });
const bindingConfig = parseAgentRouting({ version: 1, rules: [], bindings: [{ tokenId: 11, agent: "sub2api" }] });
const bound = resolveClientAgent({ "user-agent": tui, "x-ooapi-agent": "zcode", "x-ooapi-token-id": "999" }, bindingConfig.bindings, 11);
assert.equal(bound.id, "sub2api");
assert.equal(bound.source, "api-key");
assert.equal(bound.conflict, false);
assert.equal(bound.reported_client.id, "codex");
assert.equal(resolveClientAgent({ "user-agent": tui, "x-ooapi-token-id": "11" }, bindingConfig.bindings, 12).id, "codex");
assert.equal(resolveClientAgent({ "user-agent": tui }, bindingConfig.bindings, 11, false).source, "disabled");
assert.equal(publicClientAgent(bound, tui).source, "api-key");
assert.equal(publicClientAgent({ ...bound, reported_client: { id: "codex", version: "<script>", source: "user-agent", confidence: "configured", nested: { secret: true } } }).reported_client.confidence, "heuristic");
assert.equal(publicClientAgent({ ...bound, reported_client: { id: "codex", source: "user-agent", secret: true } }).reported_client.secret, undefined);
for (const bindings of [null, {}, [{ tokenId: "11", agent: "sub2api" }], [{ tokenId: 0, agent: "codex" }], [{ tokenId: 11, agent: "ooapi" }], [{ tokenId: 11, agent: "unknown" }], [{ tokenId: 11, agent: "sub2api" }, { tokenId: 11, agent: "codex" }]]) {
  assert.throws(() => parseAgentRouting({ version: 1, rules: [], bindings }));
}
assert.equal(detectClientAgent({ "user-agent": "claude-cli/2.1.0 (external, cli)" }).id, "claude-code");
assert.equal(detectClientAgent({ "x-ooapi-agent": "unknown-value" }).id, "");
assert.equal(detectClientAgent({ "user-agent": z, "x-ooapi-agent": "opencode" }).conflict, true);
assert.equal(detectClientAgent({ "user-agent": z, "x-ooapi-agent": "zcode" }).version, "3.14.3");
assert.equal(detectClientAgent({ "user-agent": z }, false).source, "disabled");
assert.equal(publicClientAgent(undefined, z).id, "zcode");
const historical = { id: 1, type: 2, device: "未知设备", user_agent: z, detail: "{}" };
const publicLog = mapLog(historical, { isAdmin: false });
assert.equal(publicLog.client_agent.id, "zcode");
assert.equal(publicLog.device, "Node.js 24");
assert.equal(Object.hasOwn(publicLog, "user_agent"), false);
assert.equal(Object.hasOwn(publicLog, "detail"), false);
assert.equal(mapLog(historical, { isAdmin: true }).user_agent, z);
const concurrent = await Promise.all([z, o].map((ua, i) => withClientAgent({ headers: { "user-agent": ua }, body: { model: "deepseek-flash", reasoning: { effort: i ? "high" : "max" } } }, async () => {
  await new Promise(resolve => setTimeout(resolve, i ? 1 : 15));
  return clientAgentAudit();
})));
assert.deepEqual(concurrent.map(a => [a.client_agent.id, a.reasoning_requested]), [["zcode", "max"], ["opencode", "high"]]);
assert.deepEqual(clientAgentAudit(), {});
assert.equal(publicClientAgent({ id: "zcode", version: "<script>", source: "secret" }).version, "");
assert.equal(safeReasoning(" HIGH "), "high");
assert.equal(safeReasoning("private invalid content"), "invalid");
assert.equal(publicRunError({ code: "INVALID_REASONING", status: 400, message: "该模型不支持所选思考强度" }), "该模型不支持所选思考强度，请在会话设定中选择模型默认。");
assert.match(publicRunError({ code: "NO_CHANNEL", reason: "COOLING" }), /冷却/);
const rule = { id: "test", enabled: true, agent: "zcode", models: ["deepseek-flash"], preferredChannels: [9, 2], reasoning: "unsupported-default", timeoutMs: 1000, retries: 0 };
const config = parseAgentRouting({ version: 1, rules: [rule] });
assert.equal(matchAgentRule(config, { id: "zcode" }, "deepseek-flash").id, "test");
assert.equal(matchAgentRule(config, { id: "zcode", conflict: true }, "deepseek-flash"), null);
assert.equal(matchAgentRule(config, { id: "opencode" }, "deepseek-flash"), null);
assert.equal(matchAgentRule(config, { id: "zcode" }, "other-model"), null);
const candidates = [{ id: 1 }, { id: 2 }, { id: 3 }];
assert.deepEqual(orderAgentChannels(candidates, rule).map(c => c.id), [2, 1, 3]);
assert.deepEqual(candidates.map(c => c.id), [1, 2, 3]);
const caps = { reasoning: { levels: ["low", "high", "max"] } };
assert.equal(agentReasoning(rule, "xhigh", caps), "xhigh");
assert.equal(agentReasoning(rule, "max", caps), "max");
assert.equal(agentReasoning({ ...rule, reasoning: "high" }, "max", caps), "high");
assert.equal(agentReasoning({ ...rule, reasoning: "high" }, "", caps), "");
for (const [ua,id] of [["sub2api/1.0.0","sub2api"],["New API","new-api"],["One-API/v0.6.1","one-api"],["litellm/1.80.0","litellm"],["OneHub/1.0","one-hub"]]) assert.equal(detectClientAgent({"user-agent":ua}).id,id);
assert.equal(detectClientAgent({"user-agent":"Go-http-client/1.1"}).id,"");
assert.equal(detectClientAgent({"user-agent":"claude-cli/2.1.0","x-ooapi-agent":"sub2api"}).conflict,false);
assert.equal(detectClientAgent({"user-agent":"NewAPI/1.0 opencode/1.18"}).id,"new-api");
assert.equal(detectClientAgent({"x-ooapi-agent":"ooapi"}).id,"");
assert.equal(mapLog({...historical,inbound_endpoint:"/api/chat/run"},{isAdmin:false}).client_agent.id,"ooapi");
assert.equal(detectClientAgent({"x-title":"One API","http-referer":"https://github.com/songquanpeng/one-api"}).id,"one-api");
for (const patch of [{ agent: "arbitrary" }, { enabled: "false" }, { timeoutMs: Infinity }, { retries: -1 }, { preferredChannels: ["2"] }, { reasoning: "ignore" }, { models: ["model*arbitrary"] }]) {
  assert.throws(() => parseAgentRouting({ version: 1, rules: [{ ...rule, ...patch }] }));
}
assert.throws(() => parseAgentRouting({ version: 1, rules: [rule, rule] }));
for (const a of CLIENT_AGENTS) if (a.icon) {
  const file = new URL(`../../ooapi-web/public/icons/agents/${a.icon}`, import.meta.url);
  assert.ok(fs.statSync(file).size > 0, `${a.name} missing icon`);
  if (a.icon.endsWith("svg")) assert.match(fs.readFileSync(file, "utf8"), /<svg\b/);
}
console.log("Agent：真实 UA、设备解析、冲突降级、历史补展示、参数校验、权限内重排与官方图标检查通过");
