import assert from "node:assert/strict";
import { requestApproval, decideApproval } from "../src/services/harness/approvals.js";
const makeRun = () => ({ userId: 11, settled: false });
const events = [];
const run = makeRun(), ctrl = new AbortController();
const args = { action: "recent" };
const promise = requestApproval(run, { tool: "account", name: "我的账号", args }, { signal: ctrl.signal, emit: e => events.push(e) });
args.action = "overview";
const id = events[0].part.id;
assert.equal(events[0].part.args.action, "recent");
assert.equal(decideApproval(run, 12, id, "approved"), false, "其他用户不得审批");
assert.equal(decideApproval(run, 11, id, "allow_everything"), false);
assert.equal(decideApproval(run, 11, id, "approved"), true);
assert.equal(await promise, true);
assert.equal(decideApproval(run, 11, id, "approved"), false, "不可重放审批");
assert.equal(run.approvals.size, 0);
assert.equal(events.at(-1).patch.status, "approved");
let pendingId;
const denied = requestApproval(run, { tool: "fetch", args: { url: "https://example.com" } }, { emit: e => { if (e.part) pendingId = e.part.id; } });
assert.equal(decideApproval(run, 11, pendingId, "denied"), true);
assert.equal(await denied, false);
const expired = requestApproval(run, { tool: "fetch", args: {} }, { timeoutMs: 5 });
await new Promise(r => setTimeout(r, 10));
assert.equal(await expired, false);
const abortRun = makeRun();
const stopped = requestApproval(abortRun, { tool: "fetch", args: {} }, { signal: ctrl.signal });
ctrl.abort();
await assert.rejects(stopped, { code: "ABORTED" });
assert.equal(abortRun.approvals.size, 0);
await assert.rejects(requestApproval(makeRun(), { tool: "fetch", args: {} }, { signal: ctrl.signal }), { code: "ABORTED" });
console.log("审批隔离、参数快照、一次性、拒绝、过期、停止回归通过");
