import assert from "node:assert/strict";
import fs from "node:fs";
import { modelCapabilities, validateCapabilities, reasoningBody, reasoningSelection } from "../src/services/model-capabilities.js";
import { validateAgentFlow, DEFAULT_AGENT_FLOW } from "../src/services/harness/policy.js";
import { compressionSplit, latestMemory, contextBudget } from "../src/services/harness/context.js";
const unknown = modelCapabilities("fixture-unknown");
const presets = JSON.parse(fs.readFileSync(new URL("../src/services/model-capabilities.json", import.meta.url), "utf8"));
for (const [id, preset] of Object.entries(presets)) {
  assert.doesNotThrow(() => validateCapabilities(preset), id);
  assert.ok(preset.sources.length > 0 && preset.sources.every(s => /^https:\/\//.test(s.url)), `${id} 缺少来源`);
}
assert.deepEqual(modelCapabilities("gpt-5.4").reasoning.levels, ["none", "low", "medium", "high", "xhigh"]);
assert.deepEqual(modelCapabilities("gemini-3.8-flash").reasoning.levels, ["low", "medium", "high"]);
assert.equal(unknown.contextWindow, null);
assert.equal(unknown.verification, "unverified");
assert.ok(contextBudget(unknown) > 0);
assert.throws(() => validateCapabilities({...unknown,contextWindow:NaN}));
assert.throws(() => validateCapabilities({...unknown,contextWindow:100,maxOutputTokens:101}));
assert.throws(() => validateCapabilities({...unknown,reasoning:{levels:["high"],defaultLevel:"max",parameter:"reasoning_effort",values:{}}}));
assert.throws(() => validateCapabilities({...unknown,reasoning:{levels:["high"],parameter:"__proto__.x",values:{}}}));
assert.deepEqual(reasoningBody({level:"high",parameter:"reasoning_effort",value:"high"},"responses"),{reasoning:{effort:"high",summary:"auto"}});
assert.deepEqual(reasoningBody({level:"high",parameter:"output_config.effort",value:"high"},"anthropic"),{thinking:{type:"adaptive"},output_config:{effort:"high"}});
assert.deepEqual(reasoningBody({level:"high",parameter:"output_config.effort",value:"high"},"chat"),{});
assert.equal(reasoningSelection("fixture-unknown","arbitrary").level,"none");
assert.equal(reasoningSelection("deepseek-flash","medium").level,"max");
assert.equal(reasoningSelection("gpt-5.4","max").level,"xhigh");
assert.equal(reasoningSelection("deepseek-flash","").level,"none");
assert.deepEqual(reasoningBody(reasoningSelection("deepseek-flash","")),{thinking:{type:"disabled"}});
assert.equal(reasoningSelection("deepseek-flash"," HIGH ").level,"high");
const conversation=[{role:"user",content:"old"},{role:"assistant",content:"done"},{role:"user",content:"new"},{role:"assistant",tool_calls:[{id:"call-a"}]},{role:"tool",tool_call_id:"call-a",content:"result"}];
const split=compressionSplit(conversation,1);
assert.equal(split.head.length,2);
assert.equal(split.tail[0].role,"user");
assert.equal(split.tail[1].tool_calls[0].id,split.tail[2].tool_call_id);
const oneTurn = [{role:"user",content:"task"}, {role:"assistant",tool_calls:[{id:"a"}]}, {role:"tool",tool_call_id:"a"}, {role:"assistant",tool_calls:[{id:"b"}]}, {role:"tool",tool_call_id:"b"}];
const toolSplit = compressionSplit(oneTurn, 1);
assert.equal(toolSplit.head.length, 3);
assert.equal(toolSplit.tail[0].tool_calls[0].id, toolSplit.tail[1].tool_call_id);
assert.equal(latestMemory([{parts:[{type:"compaction",status:"failed",summary:"bad",throughSeq:10}]}]),null);
assert.equal(latestMemory([{parts:[{type:"compaction",status:"done",summary:"saved",throughSeq:10}]}]).summary,"saved");
const flow=structuredClone(DEFAULT_AGENT_FLOW);
assert.equal(validateAgentFlow(flow).nodes.length,5);
flow.nodes.find(n=>n.kind==="tools").config.tools.push("shell");
assert.throws(()=>validateAgentFlow(flow));
const broken=structuredClone(DEFAULT_AGENT_FLOW);broken.edges=broken.edges.filter(e=>e.to!=="answer");assert.throws(()=>validateAgentFlow(broken));
const disconnected=structuredClone(DEFAULT_AGENT_FLOW);disconnected.edges=disconnected.edges.filter(e=>e.from!=="tools"&&e.to!=="tools");assert.equal(validateAgentFlow(disconnected).edges.length,3);
console.log("模型能力校验、协议映射、压缩工具配对、编排权限边界回归通过");
