import React from "react";
import { Button, Tooltip, Alert, Progress, Collapse } from "./arc/index";
import { Check, Circle, LoaderCircle } from "lucide-react";
export function Shelf({ children, className = "" }) { return <nav className={`arc-chat-shelf ${className}`}>{children}</nav>; }
export function ShelfGroup({ title, children, defaultOpen = true, action }) { return <section className="arc-chat-shelf-group"><div className="arc-chat-shelf-action">{action}</div><Collapse defaultActiveKey={defaultOpen ? ["sessions"] : []} items={[{key:"sessions",label:title,children}]}/></section>; }
export function ShelfItem({ active, icon, label, hint, onClick, actions, title }) { return <div className="arc-chat-session" data-active={active || undefined}><Tooltip title={title || label}><Button type="text" icon={icon} aria-current={active ? "page" : undefined} onClick={onClick}><span className="oo-truncate">{label}</span>{hint && <small>{hint}</small>}</Button></Tooltip>{actions}</div>; }
export function Notice({ tone = "info", title, children, actions }) { return <Alert type={tone === "warn" ? "warning" : tone} message={title} description={children} action={actions}/>; }
export function TodoPanel({ todo = [] }) { if (!todo.length) return null; const done=todo.filter(t=>t.status==="completed").length; return <Collapse defaultActiveKey={["tasks"]} items={[{key:"tasks",label:`任务清单 ${done}/${todo.length}`,children:<><Progress percent={done/todo.length*100}/><ul className="arc-chat-todos">{todo.map((t,i)=><li key={i}>{t.status==="completed"?<Check size={15}/>:t.status==="in_progress"?<LoaderCircle size={15}/>:<Circle size={15}/>}<span>{t.content}</span></li>)}</ul></>}]}/>; }
export function StreamingText({ children, streaming }) { return <div className="arc-chat-answer" aria-busy={streaming || undefined}>{children}</div>; }
